name: Seq CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Seq CI
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo bash .github/actions/build-manylinux/entrypoint.sh $(pwd)

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v') && startsWith(matrix.os, 'macos')
        uses: softprops/action-gh-release@v2
        with:
          files: seq-darwin-arm64.tar.gz

      - name: Upload Release Asset
        if: contains(github.ref, 'tags/v') && startsWith(matrix.os, 'ubuntu')
        uses: softprops/action-gh-release@v2
        with:
          files: seq-linux-x86_64.tar.gz

      - name: Upload Artifacts
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-arm64
          path: seq-darwin-arm64.tar.gz

      - name: Upload Artifacts
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-x86_64
          path: seq-linux-x86_64.tar.gz
